FROM node:24-alpine3.22 AS deps

RUN apk add --no-cache curl netcat-openbsd

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

ENV NODE_ENV=development

#EXPOSE 4016

CMD ["npm", "run", "start:dev"]
